# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b62be13ad8d8bf44a34ada911a03f13bbec1bd026027a9e006d8c6cdfe6b986e2c1ce55b15bfd2a34f81babe629860c9bc7783b44836d53b710ad9a5f8f1e5a

test:
  secret_key_base: 043e72145fc2fb0cf53661c39bcb74de6d7bf1e799b64c736f0b2152e32d186504d3933595fea1397a879a7c7340299120db2819871cc9a0db0b2c94fe41bd26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
